const fs=require('fs');const path=require('path');
function read(rel,fallback){try{return JSON.parse(fs.readFileSync(path.resolve(process.cwd(),rel),'utf8'));}catch{return fallback;}}
function write(rel,value){const file=path.resolve(process.cwd(),rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value,null,2)+'\n');}
function tokens(value){return new Set(String(value||'').toLowerCase().match(/[a-z0-9]+/g)||[]);}function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let common=0;for(const x of A)if(B.has(x))common++;return common/Math.max(A.size,B.size);}function num(...values){for(const value of values){const n=Number(value);if(Number.isFinite(n))return n;}return 0;}function queryText(row){return String(row.keys?.[0]||row.Query||row.QueryString||row.query||'').trim();}function pageText(row){return String(row.keys?.[1]||row.Page||row.Url||row.page||'').trim();}function normalizePath(value){try{return new URL(value,'https://horselegalguide.com').pathname.replace(/\/+$/,'/')||'/';}catch{return String(value||'');}}
function main(){
 const gsc=read('data/agency/gsc_snapshot.json',{}),bing=read('data/agency/bing_snapshot.json',{}),coverage=read('data/queries/query_coverage_map.json',[]),ledger=read('data/admin/consolidation_review_ledger.json',{entries:[]}),diagnostics=read('data/search/query_diagnostics.json',{items:[]}),observations=read('data/search/query_observations.json',{observations:[]});
 const coverageRows=Array.isArray(coverage)?coverage:coverage.items||[];const pageToOverlap=new Map();for(const entry of ledger.entries||[])for(const route of entry.members||[])pageToOverlap.set(route,entry.ledger_id);
 const aggregates=new Map();function add(provider,row,query,page=''){if(!query)return;const key=query.toLowerCase();const current=aggregates.get(key)||{query,providers:new Set(),clicks:0,impressions:0,positions:[],pages:new Map()};current.providers.add(provider);current.clicks+=num(row.clicks,row.Clicks);current.impressions+=num(row.impressions,row.Impressions);const position=num(row.position,row.AvgImpressionPosition,row.AveragePosition);if(position)current.positions.push(position);if(page){const route=normalizePath(page);current.pages.set(route,(current.pages.get(route)||0)+num(row.impressions,row.Impressions,1));}aggregates.set(key,current);}
 for(const row of gsc.query_page||[])add('gsc',row,queryText(row),pageText(row));for(const row of gsc.top_queries||[])add('gsc',row,queryText(row));for(const row of bing.top_queries||[])add('bing',row,queryText(row),String(row.Url||row.Page||''));
 // Grounded observations create demand/surfacing evidence without claiming literal rank.
 for(const d of diagnostics.items||[]){const key=String(d.query||'').toLowerCase();const existing=aggregates.get(key);const externallyObserved=!['UNKNOWN','PROVIDER_ERROR'].includes(d.state);if(!existing&&!externallyObserved)continue;const current=existing||{query:d.query,providers:new Set(),clicks:0,impressions:0,positions:[],pages:new Map()};if(externallyObserved)current.providers.add('gemini_google_search_grounding');current.diagnostic=d;aggregates.set(key,current);}
 const obsByPanel=new Map((observations.observations||[]).map(o=>[o.panel_id,o]));const opportunities=[];let sequence=1;
 for(const aggregate of aggregates.values()){
   let best=null;for(const row of coverageRows){const score=similarity(aggregate.query,row.query_text||row.primary_query||'');if(!best||score>best.score)best={row,score};}
   const d=aggregate.diagnostic||null;const o=d?obsByPanel.get(d.panel_id):null;const providerPages=[...aggregate.pages.entries()].sort((a,b)=>b[1]-a[1]).map(x=>x[0]);const mapped=d?.target_page||(best&&best.score>=0.55?normalizePath(best.row.target_page):'');let type='new_candidate';let target=mapped||providerPages[0]||'';const reasons=[];
   if(d&&['MISSING','WRONG_PAGE','CANNIBALIZATION'].includes(d.state)){type=d.state==='MISSING'?(target?'improve_existing':'new_candidate'):d.state==='WRONG_PAGE'?'improve_existing':'cannibalization_review';reasons.push(`active_query_${d.state.toLowerCase()}`,...(d.reasons||[]));}
   else if(providerPages.length>1){type='cannibalization_review';reasons.push('provider_query_maps_to_multiple_pages');}
   else if(mapped){type='improve_existing';reasons.push('query_matches_existing_coverage');if(pageToOverlap.has(mapped)){type='differentiate_existing';reasons.push('target_is_in_live_similarity_cluster');}}
   if(aggregate.impressions>=20&&aggregate.clicks===0)reasons.push('impressions_without_clicks');const avgPosition=aggregate.positions.length?aggregate.positions.reduce((a,b)=>a+b,0)/aggregate.positions.length:0;if(avgPosition>10)reasons.push('ranking_opportunity');
   const confidence=Math.min(0.99,0.45+(best?.score||0)*0.25+Math.min(0.15,aggregate.impressions/1000)+(d?.state&&d.state!=='UNKNOWN'?0.12:0));
   opportunities.push({opportunity_id:`provider-opportunity-${String(sequence++).padStart(4,'0')}`,query:aggregate.query,type,target_page:target,provider_pages:providerPages,providers:[...aggregate.providers],metrics:{clicks:aggregate.clicks,impressions:aggregate.impressions,average_position:Number(avgPosition.toFixed(2))},active_query_evidence:d?{panel_id:d.panel_id,state:d.state,grounded_site_surfaced:Boolean(d.evidence?.grounded_site_surfaced),competitor_urls:d.evidence?.competitor_urls||[],rank_verified:false}:null,grounded_competitors:(o?.competitors||[]).slice(0,3),coverage_match_score:Number((best?.score||0).toFixed(3)),confidence:Number(confidence.toFixed(3)),reasons:[...new Set(reasons)],status:'pending_owner_review',automatic_actions_completed:['measurement','classification','competitor_observation'],automatic_approval:false,automatic_publication:false,live_page_change_authorized:false});
 }
 opportunities.sort((a,b)=>b.metrics.impressions-a.metrics.impressions||b.confidence-a.confidence||a.query.localeCompare(b.query));const summary={opportunities:opportunities.length,new_candidates:opportunities.filter(x=>x.type==='new_candidate').length,improve_existing:opportunities.filter(x=>x.type==='improve_existing').length,differentiate_existing:opportunities.filter(x=>x.type==='differentiate_existing').length,cannibalization_review:opportunities.filter(x=>x.type==='cannibalization_review').length,active_query_failures:opportunities.filter(x=>['MISSING','WRONG_PAGE','CANNIBALIZATION'].includes(x.active_query_evidence?.state)).length};
 const output={schema_version:'2.0.0',generated_at:new Date().toISOString(),provider_status:{gsc:gsc.status||'unknown',bing:bing.status||'unknown',grounded_search:observations.provider_state||'NOT_CONFIGURED'},summary,policy:'Provider and grounded-search data may create recommendations, pending candidates, and finished owner-review repairs only. They may not approve, publish, or mutate live legal pages.',truth_boundary:'Grounded web surfacing is evidence of live cited sources, not literal organic rank. GSC is the source for owned-site Google clicks, impressions, CTR, and average position.',opportunities};write('data/query_intelligence/provider_opportunities.json',output);write('reports/query_intelligence/provider_opportunities.json',output);console.log(`Provider query intelligence generated: ${opportunities.length} opportunities.`);return output;
}
if(require.main===module)main();module.exports={main,similarity};
