const fs=require('fs');const path=require('path');function read(r,f){try{return JSON.parse(fs.readFileSync(path.resolve(process.cwd(),r),'utf8'));}catch{return f;}}function write(r,v){const p=path.resolve(process.cwd(),r);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');}
function classify(status,configured){if(status==='ok'||status==='CONNECTED')return 'CONNECTED';if(!configured)return 'NOT_CONFIGURED';if(['warning','DEGRADED','provider_error'].includes(status))return 'DEGRADED';return 'DISCONNECTED';}
// One provider_state for the whole observer hid which provider actually
// answered. Both search providers are reported separately now, derived from the
// per-observation attempt log, so a run carried by OpenRouter can never be read
// as evidence that Gemini grounding works - it does not on this project, where
// it returns 429 RESOURCE_EXHAUSTED.
function searchProviderState(q,name,configured){
  const obs=q.observations||[];
  if(obs.some(o=>o.status==='ok'&&o.provider===name))return 'CONNECTED';
  if(obs.some(o=>(o.provider_attempts||[]).some(a=>a.provider===name&&a.status!=='ok')))return 'DEGRADED';
  if(!configured)return 'NOT_CONFIGURED';
  return obs.length?'DISCONNECTED':'UNKNOWN';
}
function main(){const g=read('data/agency/gsc_snapshot.json',{}),b=read('data/agency/bing_snapshot.json',{}),q=read('data/search/query_observations.json',{}),idx=read('_ops/reports/indexnow-submit-report.json',{});const providers={openrouter_web_search:{state:searchProviderState(q,'openrouter_web_search',Boolean(process.env.OPENROUTER_API_KEY)),configured:Boolean(process.env.OPENROUTER_API_KEY),role:'primary_citation_observer',capabilities:{live_web:true,grounded_citations:true,literal_organic_rank:false}},gemini_grounded_search:{state:searchProviderState(q,'gemini_google_search_grounding',Boolean(process.env.GEMINI_API_KEY)),configured:Boolean(process.env.GEMINI_API_KEY),role:'fallback_citation_observer',note:'Grounded google_search tool use returns 429 RESOURCE_EXHAUSTED on this project; plain generateContent returns 200.',capabilities:{live_web:true,grounded_citations:true,literal_organic_rank:false}},live_query_observer:{state:String(q.provider_state||'NOT_CONFIGURED'),stop:q.stop||null,primary_provider:q.primary_provider||null,capabilities:{live_web:true,grounded_citations:true,literal_organic_rank:false}},gsc:{state:classify(g.status,Boolean(process.env.GSC_ACCESS_TOKEN||process.env.GSC_SERVICE_ACCOUNT_JSON||(process.env.GSC_SERVICE_ACCOUNT_EMAIL&&process.env.GSC_PRIVATE_KEY))),capabilities:{search_analytics:true,sitemaps:true,url_inspection:true,force_indexing:false}},bing:{state:classify(b.status,Boolean(process.env.BING_WEBMASTER_API_KEY)),capabilities:{traffic:true,crawl_stats:true,query_stats:true}},indexnow:{state:idx.status==='success'?'CONNECTED':idx.status==='dry-run'?'DRY_RUN_ONLY':idx.status==='failed'?'DEGRADED':'UNKNOWN',capabilities:{submission:true}}};const out={schema_version:'1.0.0',generated_at:new Date().toISOString(),providers,truth_boundary:'Presence of a script is not provider proof. Only a successful external receipt can mark live provider behavior as connected/successful.'};write('data/system/provider_health.json',out);return out;}if(require.main===module)console.log(JSON.stringify(main(),null,2));module.exports={main};
