const fs = require('fs');
const path = require('path');
const ROOT = process.cwd();
function ensure(p){fs.mkdirSync(p,{recursive:true});}
function writeJson(rel,data){const p=path.join(ROOT,rel);ensure(path.dirname(p));fs.writeFileSync(p,JSON.stringify(data,null,2)+'\n');}
function exists(rel){return fs.existsSync(path.join(ROOT,rel));}
const workflows=[
  {file:'build.yml',purpose:'manual build artifact lane',commands:['npm run build','npm run ops:trace-workflows'],artifacts:['dist/index.html','.build/distribution-manifest.json']},
  {file:'self-heal-loop.yml',purpose:'scheduled detect-repair-revalidate loop; non-content repairs only, drafts stay with the approval lane',commands:['npm run selfheal','npm run validate:self-heal-loop'],artifacts:['_ops/selfheal/heal_until_clean.js','_ops/validators/validate_self_heal_loop.js','_ops/reports/self-heal-loop.json']},
  {file:'validate.yml',purpose:'repo validation lane',commands:['npm run validate:preflight','npm run build','npm run ops:trace-workflows','npm run validate:all'],artifacts:['data/admin/workflow_health.json','dist/admin/index.html']},
  {file:'drafts-refresh.yml',purpose:'generation + self-heal + prevalidation + admin refresh',commands:['npm run generate:drafts','npm run content:self-heal','npm run content:prevalidate','npm run build','npm run ops:trace-workflows','npm run publish:mode','npm run validate:all'],artifacts:['content/drafts/generated','data/admin/editorial_manifest.json','data/admin/content_quality_report.json','data/admin/self_heal_report.json','data/admin/prevalidation_report.json']},
  {file:'public-signal-processing.yml',purpose:'public/social signal ingestion',commands:['npm run collect:signals','npm run normalize:signals','npm run map:signals','npm run report:ingestion','npm run build','npm run ops:trace-workflows','npm run validate:all'],artifacts:['reference/signal_trace.json','data/community/collection_status.json','data/community/ingestion_report.json','data/admin/signal_ingestion_status.json']},
  {file:'publish.yml',purpose:'manual publish lane',commands:['npm run state:publish','npm run validate:preflight','npm run build','npm run publish:mode','npm run ops:trace-workflows','npm run validate:all','./distribution_scripts/indexnow_submit.sh .build/indexnow-priority.txt .build/indexnow-batch.txt','python3 distribution_scripts/gsc_submit_sitemaps.py','python3 distribution_scripts/gsc_inspect_urls.py .build/distribution-priority-urls.txt'],artifacts:['data/publish_state.json','dist/editorial-publishing-state.json','.build/indexnow-priority.txt']},
  {file:'deploy-distribution.yml',purpose:'post-Manual-Publish distribution/indexing lane',commands:['npm run build','npm run validate:all','npm run distribution:post-publish','npm run validate:indexnow-workflow','npm run validate:authority-distribution'],artifacts:['data/distribution/provider_receipt.json','data/distribution/observation_feedback.json','.build/distribution-priority-urls.txt']},
  {file:'sitemap-indexing.yml',purpose:'manual indexing utility',commands:['npm run build','./distribution_scripts/indexnow_submit.sh','python3 distribution_scripts/gsc_submit_sitemaps.py','python3 distribution_scripts/gsc_inspect_urls.py .build/distribution-priority-urls.txt'],artifacts:['dist/sitemap.xml','dist/sitemap-pages.xml']},
  {file:'editorial-continuity.yml',purpose:'scheduled pending-only editorial runway replenishment',commands:['npm run validate:protected-editorial-core','npm run authority:cycle','npm run continuity:replenish','npm run generate:drafts','npm run content:self-heal','npm run content:prevalidate','npm run build','npm run validate:all'],artifacts:['scripts/continuity/replenish_editorial_runway.mjs','data/continuity/editorial_continuity_report.json']},
  {file:'admin-bulk-content-actions.yml',purpose:'owner admin bulk action lane; existing method preserved and authenticated dispatch added',commands:['npm run content:self-heal','npm run content:prevalidate','npm run build','npm run ops:trace-workflows','dry-run admin action','npm run build','npm run validate:all'],artifacts:['scripts/admin/approve_many.js','scripts/admin/reject_many.js','scripts/admin/set_publish_date_many.js','scripts/admin/write_action_receipt.js','data/admin/editorial_manifest.json']},
  {file:'admin-maintenance.yml',purpose:'authenticated self-heal/prevalidation and validation lane without approval-state changes',commands:['npm run content:self-heal','npm run content:prevalidate','npm run build','npm run validate:all'],artifacts:['scripts/quality/run_self_heal.js','scripts/quality/run_prevalidation.js','scripts/admin/write_action_receipt.js']},
  {file:'agency-search-monitor.yml',purpose:'scheduled and authenticated GSC/Bing/live monitoring plus recommendation refresh',commands:['node scripts/agency/refresh_search_health.js','node scripts/query/build_provider_query_intelligence.js','node scripts/remediation/build_remediation_queue.js','npm run build','npm run validate:agency-monitoring'],artifacts:['data/agency/dashboard.json','data/query_intelligence/provider_opportunities.json','data/remediation/remediation_queue.json']},
  {file:'query-intelligence.yml',purpose:'provider opportunity rebuild and owner-selected pending draft admission',commands:['node scripts/query/build_provider_query_intelligence.js','node scripts/query/admit_provider_candidates.js','npm run generate:drafts','npm run content:self-heal','npm run content:prevalidate','npm run validate:all'],artifacts:['data/query_intelligence/provider_opportunities.json','scripts/query/admit_provider_candidates.js']},
  {file:'page-remediation.yml',purpose:'separate owner approval and apply gates for existing-page search remediation',commands:['node scripts/remediation/manage_remediations.js','npm run build','npm run validate:all'],artifacts:['data/remediation/remediation_queue.json','data/remediation/applied_search_controls.json','scripts/remediation/manage_remediations.js']},
  {file:'approved-content-email.yml',purpose:'approved content social email lane for Claire; simulated as dry-run/preview only',commands:['npm run build','python3 scripts/social/send_approved_content_email.py --dry-run'],artifacts:['scripts/social/send_approved_content_email.py','data/social/approved_content_email_state.json','reports/approved-content-email-preview.md']},
  {file:'query-page-repair.yml',purpose:'owner-gated query-page repair approval/apply lane',commands:['node scripts/remediation/manage_remediations.js','npm run build','npm run validate:all'],artifacts:['data/remediation/remediation_queue.json','data/remediation/applied_search_controls.json','scripts/remediation/manage_remediations.js']}
];
function readJson(rel,fallback){try{return JSON.parse(fs.readFileSync(path.join(ROOT,rel),'utf8'));}catch{return fallback;}}
function main(){const trace=[]; const actualWorkflows=fs.readdirSync(path.join(ROOT,'.github/workflows')).filter(f=>/\.ya?ml$/.test(f)).sort(); const specWorkflows=workflows.map(w=>w.file).sort(); const inventoryErrors=[]; for(const f of actualWorkflows) if(!specWorkflows.includes(f)) inventoryErrors.push(`workflow missing simulation spec: ${f}`); for(const f of specWorkflows) if(!actualWorkflows.includes(f)) inventoryErrors.push(`simulation spec references missing workflow: ${f}`); const collection=readJson('data/community/collection_status.json',{}); const signalStatus=readJson('data/admin/signal_ingestion_status.json',{}); const failedSources=(collection.adapter_status||[]).filter(s=>s.status==='failed'); const fresh=Number(collection.collected_count||0); const zeroReddit=Boolean(collection.zero_reddit_warning)||Number(collection.reddit_collected_count||0)===0; for(const wf of workflows){const yamlExists=exists(`.github/workflows/${wf.file}`); const artifactRows=wf.artifacts.map(a=>({path:a,exists:exists(a),status:exists(a)?'present':'missing'})); const hard_fails=[]; const warnings=[]; const live_followups=[]; if(!yamlExists) hard_fails.push('workflow YAML missing'); for(const a of artifactRows) if(!a.exists) hard_fails.push(`expected artifact missing: ${a.path}`); if(wf.file==='public-signal-processing.yml'){ if(fresh===0) live_followups.push('0 fresh public/social signals collected in local container simulation; stored signal corpus still normalized/mapped. Live GitHub run should confirm fresh collection.'); if(zeroReddit) live_followups.push('Reddit produced 0 fresh signals in local container simulation; live GitHub run should be reviewed.'); if(failedSources.length) warnings.push(`${failedSources.length} signal sources failed during local simulation.`); }
    if(wf.file==='deploy-distribution.yml'||wf.file==='sitemap-indexing.yml'||wf.file==='publish.yml') live_followups.push('Live IndexNow/GSC submission is dry-run/non-blocking in local simulation; prove live after apply.');
    const row={workflow:wf.file,path:`.github/workflows/${wf.file}`,purpose:wf.purpose,mode:'local_simulated_github_actions_data_trace',execution_model:'receipt_aggregation_from_local_validation_and_artifact_presence_not_independent_reexecution',commands:wf.commands.map(cmd=>({cmd,status:'covered_by_prior_local_validation_or_dry_run_not_independently_reexecuted_here',exit_code:null,log:'see reports/github-actions-simulation/ and local validation logs generated by the operator run'})),artifacts:artifactRows,warnings,live_followups,hard_fails,status:hard_fails.length?'failed':(warnings.length?'passed_with_warnings':'passed'),truth_boundary:'Local simulation only. Does not prove live GitHub Actions, live secrets, live GSC, live IndexNow, or deployed runtime.'}; writeJson(`reports/github-actions-simulation/${wf.file.replace(/\.ya?ml$/,'.json')}`,row); trace.push(row); }
  const summary={generated_at:new Date().toISOString(),inventory_errors:inventoryErrors,truth_boundary:'This is a local simulated GitHub Actions data trace. It combines workflow YAML presence, local command validation already executed in this workspace, artifact presence, dry-run distribution checks, and source-specific warning inspection. It does not prove live GitHub Actions, live GitHub secrets, live GSC, live IndexNow, or deployed runtime behavior.',status:(inventoryErrors.length||trace.some(r=>r.status==='failed'))?'failed':(trace.some(r=>r.status==='passed_with_warnings')?'passed_with_warnings':'passed'),workflow_count:trace.length,passed:trace.filter(r=>r.status==='passed').length,passed_with_warnings:trace.filter(r=>r.status==='passed_with_warnings').length,failed:trace.filter(r=>r.status==='failed').length+inventoryErrors.length,hostile_review_repairs:[{finding:'public-signal-processing total runtime was too short for sequential sources',repair:'separated SIGNAL_COLLECTION_RUNTIME_MS from per-source SIGNAL_SOURCE_TIMEOUT_MS and set workflow total runtime to 90000ms'},{finding:'/admin/seo was previously mostly manifest-score based',repair:'dashboard now measures rendered dist HTML, sitemap files, schema coverage, internal links, signal health, workflow trace, and GitHub Actions simulation trace'}],live_followups_count:trace.reduce((n,r)=>n+(r.live_followups||[]).length,0),workflows:trace.map(r=>({workflow:r.workflow,status:r.status,warnings:r.warnings,live_followups:r.live_followups||[],hard_fails:r.hard_fails,report:`reports/github-actions-simulation/${r.workflow.replace(/\.ya?ml$/,'.json')}`}))}; writeJson('reports/github-actions-simulation/summary.json',summary); writeJson('data/admin/github_actions_trace.json',summary); console.log(`GitHub Actions simulation trace: ${summary.status} (${summary.passed} passed, ${summary.passed_with_warnings} warnings, ${summary.failed} failed).`); if(summary.failed) process.exitCode=1;}
if(require.main===module) main(); module.exports={main};
