#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const ROOT=process.cwd();function readJson(rel,f={}){try{return JSON.parse(fs.readFileSync(path.resolve(ROOT,rel),'utf8'))}catch{return f}}function write(rel,v){const p=path.resolve(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')}
function b64(v){return Buffer.from(v).toString('base64url')}
async function jsonFetch(url,opt={}){const r=await fetch(url,{...opt,signal:AbortSignal.timeout(25000)});const t=await r.text();let body={};try{body=t?JSON.parse(t):{}}catch{body={raw:t.slice(0,1000)}}if(!r.ok)throw new Error(`${r.status} ${r.statusText}: ${JSON.stringify(body).slice(0,600)}`);return body}
function serviceAccount(){if(process.env.GSC_SERVICE_ACCOUNT_JSON){try{return JSON.parse(process.env.GSC_SERVICE_ACCOUNT_JSON)}catch(e){throw new Error(`GSC_SERVICE_ACCOUNT_JSON invalid: ${e.message}`)}}return {client_email:process.env.GSC_SERVICE_ACCOUNT_EMAIL,private_key:String(process.env.GSC_PRIVATE_KEY||'').replace(/\\n/g,'\n')}}
async function token(scope='https://www.googleapis.com/auth/webmasters'){if(process.env.GSC_ACCESS_TOKEN)return process.env.GSC_ACCESS_TOKEN;const sa=serviceAccount();if(!sa.client_email||!sa.private_key)return null;const now=Math.floor(Date.now()/1000);const h=b64(JSON.stringify({alg:'RS256',typ:'JWT'})),pl=b64(JSON.stringify({iss:sa.client_email,scope,aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const input=`${h}.${pl}`;const sig=crypto.sign('RSA-SHA256',Buffer.from(input),sa.private_key).toString('base64url');const r=await jsonFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${input}.${sig}`})});return r.access_token}
function siteUrl(){return process.env.GSC_SITE_URL||'sc-domain:horselegalguide.com'}function siteDomain(){return String(process.env.SITE_DOMAIN||'https://horselegalguide.com').replace(/\/$/,'')}
async function submitSitemaps(){const access=await token();const s=siteUrl(),cfg=readJson('distribution.config.json',{sitemaps:['dist/sitemap.xml','dist/sitemap-pages.xml']});if(!access){const out={provider:'gsc',operation:'submit_sitemaps',status:'skipped_not_configured',executed_at:new Date().toISOString(),site_url:s,submitted:[],failures:['GSC credentials are not configured.']};write('_ops/reports/gsc-sitemap-submit-report.json',out);return out}const submitted=[],failures=[];for(const local of cfg.sitemaps||[]){const url=`${siteDomain()}/${path.basename(local)}`;const endpoint=`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(s)}/sitemaps/${encodeURIComponent(url)}`;try{await jsonFetch(endpoint,{method:'PUT',headers:{authorization:`Bearer ${access}`}});submitted.push({sitemap:url,status:'success'})}catch(e){failures.push({sitemap:url,error:e.message})}}const out={provider:'gsc',operation:'submit_sitemaps',status:failures.length?(submitted.length?'partial':'failed'):'success',executed_at:new Date().toISOString(),site_url:s,submitted,failures};write('_ops/reports/gsc-sitemap-submit-report.json',out);return out}
async function inspectUrls(){const access=await token('https://www.googleapis.com/auth/webmasters.readonly');const s=siteUrl(),file=process.env.GSC_INSPECTION_FILE||'.build/distribution-priority-urls.txt';const limit=Math.max(1,Math.min(50,Number(process.env.GSC_INSPECTION_LIMIT||20)));const urls=fs.existsSync(path.resolve(ROOT,file))?fs.readFileSync(path.resolve(ROOT,file),'utf8').split(/\r?\n/).map(x=>x.trim()).filter(x=>/^https?:\/\//.test(x)).slice(0,limit):[];if(!access){const out={provider:'gsc',operation:'url_inspection',status:'skipped_not_configured',executed_at:new Date().toISOString(),site_url:s,inspections:[],failures:['GSC credentials are not configured.']};write('_ops/reports/gsc-url-inspection-report.json',out);return out}const inspections=[];for(const url of urls){try{const body=await jsonFetch('https://searchconsole.googleapis.com/v1/urlInspection/index:inspect',{method:'POST',headers:{authorization:`Bearer ${access}`,'content-type':'application/json'},body:JSON.stringify({inspectionUrl:url,siteUrl:s,languageCode:'en-US'})});const r=body.inspectionResult||{};inspections.push({url,status:'success',indexStatusResult:r.indexStatusResult||{},mobileUsabilityResult:r.mobileUsabilityResult||{},richResultsResult:r.richResultsResult||{}})}catch(e){inspections.push({url,status:'failed',error:e.message})}}const failed=inspections.filter(x=>x.status==='failed').length;const out={provider:'gsc',operation:'url_inspection',status:failed?(failed===inspections.length?'failed':'partial'):'success',executed_at:new Date().toISOString(),site_url:s,inspection_note:'URL Inspection reports Google index status; it does not request or force indexing.',inspections,failures:failed};write('_ops/reports/gsc-url-inspection-report.json',out);return out}
const cmd=process.argv[2]||'all';const result={};if(cmd==='submit-sitemaps'||cmd==='all')result.sitemaps=await submitSitemaps();if(cmd==='inspect'||cmd==='all')result.inspection=await inspectUrls();console.log(JSON.stringify(result,null,2));if(Object.values(result).some(x=>x?.status==='failed'))process.exitCode=2;
