#!/usr/bin/env node
// Emit REPO_VALIDATION_MATRIX.md from what the validators actually do.
//
// README documents that `validate:foundation:audit` softens only validators
// built on the shared createReport() helper, and that legacy validators calling
// fail() or exiting non-zero stay blocking in both modes. That caveat was true
// but unquantified, so nobody could tell which validators it applied to.
//
// This derives the answer by inspection rather than by assertion: a validator
// that references createReport( is softenable in audit mode; anything else is
// always blocking. Regenerate with `npm run validation:matrix`.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const scripts = pkg.scripts || {};

const rows = [];
const composites = [];
for (const [name, cmd] of Object.entries(scripts)) {
  if (!name.startsWith('validate:')) continue;
  const m = cmd.trim().match(/^node (?:--\S+ )*([\w./-]+\.(?:js|mjs))$/);
  if (!m) { composites.push({ name, cmd }); continue; }
  const file = m[1];
  const abs = path.join(ROOT, file);
  if (!fs.existsSync(abs)) { rows.push({ name, file, mode: 'MISSING_FILE' }); continue; }
  const src = fs.readFileSync(abs, 'utf8');
  rows.push({ name, file, mode: src.includes('createReport(') ? 'SOFTENABLE' : 'ALWAYS_BLOCKING' });
}
rows.sort((a, b) => a.name.localeCompare(b.name));

const soft = rows.filter((r) => r.mode === 'SOFTENABLE');
const hard = rows.filter((r) => r.mode === 'ALWAYS_BLOCKING');
const missing = rows.filter((r) => r.mode === 'MISSING_FILE');
const pct = (n) => `${Math.round((n / rows.length) * 100)}%`;

const md = `# Repo Validation Matrix — horse-legal-guide-velocity

Generated by \`npm run validation:matrix\` from package.json and the validator
sources. Do not hand-edit; regenerate instead.

## What decides whether a validator blocks

This repo already has a severity mechanism: \`validate:foundation:audit\` softens
validators built on the shared \`createReport()\` helper, while
\`validate:foundation:enforce\` blocks on everything. README states that legacy
validators calling \`fail()\` or exiting non-zero directly stay blocking in both
modes, so audit mode is not a globally non-blocking pass.

That caveat applies more widely than it reads:

| Class | Count | Share | Behaviour in audit mode |
|---|---:|---:|---|
| \`SOFTENABLE\` — uses \`createReport()\` | ${soft.length} | ${pct(soft.length)} | Downgraded to a report; does not block |
| \`ALWAYS_BLOCKING\` — legacy \`fail()\` / \`exit(1)\` | ${hard.length} | ${pct(hard.length)} | Blocks in audit **and** enforce |
${missing.length ? `| \`MISSING_FILE\` | ${missing.length} | ${pct(missing.length)} | Script points at a file that does not exist |\n` : ''}
**${hard.length} of ${rows.length} single-command validators ignore audit mode.**
Treat audit mode as "softens a quarter of the suite", not as a dry run.

Migrating a legacy validator to \`createReport()\` is what moves it from the
second table to the first. Nothing here changes behaviour; it records it.

## Softenable in audit mode (${soft.length})

| Validator | Source |
|---|---|
${soft.map((r) => `| \`npm run ${r.name}\` | \`${r.file}\` |`).join('\n')}

## Always blocking (${hard.length})

| Validator | Source |
|---|---|
${hard.map((r) => `| \`npm run ${r.name}\` | \`${r.file}\` |`).join('\n')}
${missing.length ? `\n## Broken references (${missing.length})\n\n${missing.map((r) => `- \`npm run ${r.name}\` -> missing \`${r.file}\``).join('\n')}\n` : ''}
## Composite gates (${composites.length})

These chain other validators with \`&&\`, so they inherit the severity of
whichever member fails first and stop there.

${composites.map((c) => `- \`npm run ${c.name}\``).join('\n')}
`;

fs.writeFileSync(path.join(ROOT, 'REPO_VALIDATION_MATRIX.md'), md);
console.log(`VALIDATION MATRIX GENERATED: ${rows.length} single-command validators (${soft.length} softenable, ${hard.length} always blocking, ${missing.length} missing), ${composites.length} composites`);
