#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';
const RUN=process.env.CONTINUITY_RUN_DATE||new Date().toISOString().slice(0,10),HORIZON=Number(process.env.CONTINUITY_HORIZON_DAYS||120),DRY=process.argv.includes('--dry-run');
// Cadence policy: 2026 is locked and client-approved; the from_2027 lane is
// adjustable without touching this generator. Both lanes emit status:pending
// entries that still require manual admin approval, so cadence controls how much
// is PROPOSED, never what is published.
const POLICY=(()=>{try{return JSON.parse(fs.readFileSync('data/continuity/cadence_policy.json','utf8'))}catch{return null}})();
const LOCKED_THROUGH=POLICY?.locked_through||'2026-12-31';
function laneFor(dateStr){const l=POLICY?.lanes||{};return dateStr>LOCKED_THROUGH?(l.from_2027||l.locked_2026||{}):(l.locked_2026||{});}
const backlog=JSON.parse(fs.readFileSync('data/system/editorial_backlog.json','utf8')),calendar=JSON.parse(fs.readFileSync('data/system/content_calendar.json','utf8')),targets=JSON.parse(fs.readFileSync('data/queries/page_targets.json','utf8'));const ms=86400000,runD=new Date(RUN+'T00:00:00Z'),maxDate=backlog.map(x=>x.date).sort().at(-1)||RUN,maxD=new Date(maxDate+'T00:00:00Z'),days=Math.floor((maxD-runD)/ms),targetD=new Date(runD.getTime()+HORIZON*ms),existing=new Set(backlog.map(x=>x.entry_id)),newEntries=[];let d=new Date(maxD.getTime()+ms),i=0;
function iso(x){return x.toISOString().slice(0,10)}function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90)}
function add(date,type,cadence,target){const base=target?.title||target?.primary_query||target?.cluster||'equine legal planning';const id=`continuity-${type}-${date}-${slug(base).slice(0,54)}`;if(existing.has(id))return;const title=type==='insight'?`A Plain-English Note on ${base}`:type==='article'?`${base}: A Practical Guide to the Questions That Usually Matter Most`:type==='whitepaper'?`${base}: A Deeper Equine Legal Reference`: `${base}: Quarterly Authority Review`;const s=slug(title);newEntries.push({entry_id:id,date,title,content_type:type,cadence,status:'pending',source_page_id:target?.page_id||null,source_cluster:target?.cluster||'general-equine-legal',source_query_title:target?.primary_query||target?.title||null,slug:`/drafts/${date}/${s}/`,github_path:`content/drafts/generated/${date}__${s}.md`,notes:'Rolling continuity draft generated for the existing manual review and approval workflow.',review_status:'pending',continuity_generated:true,continuity_policy:'rolling_120_day_pending_draft_runway'});existing.add(id);}
while(d<=targetD){const date=iso(d),t=targets[i%targets.length],lane=laneFor(date);if(lane.insight_every_day!==false)add(date,'insight','daily',t);if(d.getUTCDay()===(lane.article_weekday??2))add(date,'article','weekly',targets[(i+37)%targets.length]);if(d.getUTCDate()===(lane.whitepaper_day_of_month??1))add(date,'whitepaper','monthly',targets[(i+71)%targets.length]);if(d.getUTCDate()===1&&(lane.deep_authority_months??[0,3,6,9]).includes(d.getUTCMonth()))add(date,'deep_authority','quarterly',targets[(i+103)%targets.length]);d=new Date(d.getTime()+ms);i++;}
const report={schema_version:'1.0',run_date:RUN,horizon_days:HORIZON,last_existing_editorial_date:maxDate,days_of_existing_runway:days,new_pending_entries:newEntries.length,dry_run:DRY,publication_authority:'EXISTING_HORSE_MANUAL_ADMIN_APPROVAL_FLOW',cadence_policy_locked_through:LOCKED_THROUGH};fs.mkdirSync('data/continuity',{recursive:true});fs.writeFileSync('data/continuity/editorial_continuity_report.json',JSON.stringify(report,null,2)+'\n');if(!DRY&&newEntries.length){backlog.push(...newEntries);for(const e of newEntries)calendar.push({date:e.date,entry_id:e.entry_id,status:'pending',generation_validation_status:'pending_generation',review_status:'pending',publish_date:null,self_heal_status:'pending',prevalidation_status:'pending'});backlog.sort((a,b)=>a.date.localeCompare(b.date)||a.entry_id.localeCompare(b.entry_id));calendar.sort((a,b)=>a.date.localeCompare(b.date)||a.entry_id.localeCompare(b.entry_id));fs.writeFileSync('data/system/editorial_backlog.json',JSON.stringify(backlog,null,2)+'\n');fs.writeFileSync('data/system/content_calendar.json',JSON.stringify(calendar,null,2)+'\n');}console.log(JSON.stringify(report,null,2));
