const fs=require('fs');const path=require('path');
function fail(m){console.error(`REMEDIATION_WORKFLOW_FAIL: ${m}`);process.exitCode=1;}
function read(rel){const p=path.resolve(process.cwd(),rel);if(!fs.existsSync(p)){fail(`${rel} missing`);return '';}return fs.readFileSync(p,'utf8');}
function json(rel){try{return JSON.parse(read(rel));}catch(e){fail(`${rel} invalid JSON: ${e.message}`);return {};}}
for(const rel of ['scripts/remediation/build_remediation_queue.js','scripts/remediation/manage_remediations.js','scripts/remediation/apply_search_controls.js','.github/workflows/page-remediation.yml','data/remediation/remediation_queue.json','data/remediation/applied_search_controls.json','reports/remediation/remediation_queue.json'])read(rel);
const queue=json('data/remediation/remediation_queue.json');const controls=json('data/remediation/applied_search_controls.json');
if(!String(queue.policy||'').toLowerCase().includes('owner approval'))fail('Remediation queue must require owner approval.');
const statuses=new Set(['pending_owner_approval','approved','applied','rejected']);const actions=new Set(['noindex_keep_llm','canonical_to_primary','redirect_to_primary','differentiate_patch']);const byId=new Map();
for(const proposal of queue.proposals||[]){byId.set(proposal.proposal_id,proposal);if(!statuses.has(proposal.status))fail(`${proposal.proposal_id} invalid status ${proposal.status}`);if(proposal.approval_required_for_live_change!==true||proposal.automatic_live_change!==false)fail(`${proposal.proposal_id} does not preserve owner gate`);if(['approved','applied'].includes(proposal.status)){if(!actions.has(proposal.approved_action)||!proposal.approved_by||!proposal.approved_at)fail(`${proposal.proposal_id} lacks complete approval evidence`);}if(proposal.status==='applied'&&!proposal.applied_at)fail(`${proposal.proposal_id} lacks applied_at evidence`);}
for(const control of controls.controls||[]){const proposal=byId.get(control.proposal_id);if(!proposal)fail(`Control ${control.route} has no source proposal`);else{if(proposal.status!=='applied')fail(`Control ${control.route} source proposal is not applied`);if(control.action!==proposal.approved_action)fail(`Control ${control.route} action differs from approved action`);if(!control.approved_by||!control.approved_at||!control.applied_by||!control.applied_at)fail(`Control ${control.route} lacks durable owner/apply evidence`);}}
const manage=read('scripts/remediation/manage_remediations.js');for(const marker of ["proposal.status!=='approved'","is not owner-approved","requires a reviewed patch_plan","automatic_approval:false","automatic_live_change:false"])if(!manage.includes(marker))fail(`Remediation manager missing guard ${marker}`);
const apply=read('scripts/remediation/apply_search_controls.js');if(!apply.includes('data/remediation/applied_search_controls.json'))fail('Build remediation layer is not driven by approved controls.');
const workflow=read('.github/workflows/page-remediation.yml');for(const marker of ['Owner Approved Page Remediation','workflow_dispatch:','approved_action','manage_remediations.js','validate:all','Upload remediation evidence'])if(!workflow.includes(marker))fail(`Remediation workflow missing ${marker}`);
if(!(controls.controls||[]).length){const redirects=read('dist/_redirects');if(redirects.includes('# BEGIN OWNER-APPROVED REMEDIATIONS'))fail('Build contains remediation redirects without any approved controls.');}
if(!process.exitCode)console.log(`Owner-approved remediation contract OK (${(queue.proposals||[]).length} proposals, ${(controls.controls||[]).length} applied controls; no automatic live mutation).`);
