const fs=require('fs');function t(p){if(!fs.existsSync(p))throw new Error(`missing ${p}`);return fs.readFileSync(p,'utf8')}function ok(c,m){if(!c)throw new Error(m)}
const cycle=t('package.json'),obs=t('scripts/search/live_query_observer.js'),diag=t('scripts/search/build_query_diagnostics.js'),prep=t('scripts/search/prepare_query_repairs.js'),manage=t('scripts/search/manage_query_repairs.js'),workflow=t('.github/workflows/query-page-repair.yml'),admin=t('functions/_shared/github_admin.js');
const blackoutReport=t('scripts/search/report_provider_blackout.mjs'),monitor=t('.github/workflows/agency-search-monitor.yml');
ok(cycle.includes('search:cycle')&&cycle.includes('search:prepare-repairs'),'search cycle incomplete');ok(obs.includes('google_search')&&obs.includes('competitors'),'live observation/competitor evidence missing');ok(diag.includes('MISSING')&&diag.includes('WRONG_PAGE')&&diag.includes('CANNIBALIZATION'),'query diagnosis states missing');ok(prep.includes('approval_required:true')&&prep.includes('automatic_live_change:false'),'owner-review repair boundary missing');ok(manage.includes("if(!r.owner_approved||!r.approved_at)"),'apply can bypass owner approval');ok(manage.includes('was already applied; wait for the external retest'),'query repair can be applied twice before retest');ok(prep.includes('bounded_repair_revisions')||prep.includes('maxRevisions=2'),'bounded second-repair contract missing');ok(workflow.includes('Owner Approved Query Page Repair')&&workflow.includes('validate:all'),'owner-gated repair workflow missing validation');ok(admin.includes("'approve_query_repair'")&&admin.includes("'apply_query_repair'"),'GitHub admin query-repair controls missing');ok(!/automatic_approval\s*:\s*true/i.test(obs+diag+prep+manage),'automatic legal-content approval detected');// A provider blackout must be discriminated, never blanket-greened. Owner-held
// billing/credential/quota conditions (401/402/403/429, or no key) stop with a
// name and exit 0; every other failure shape - 5xx, connection failure, a body
// that will not parse - must still fail this lane red, or a genuine provider
// break becomes a silent no-op. Both branches are asserted here so neither can
// be removed without this validator going red.
ok(obs.includes('OWNER_HELD_HTTP_STATUS')&&[401,402,403,429].every(code=>new RegExp(`\\b${code}\\b`).test(obs.split('OWNER_HELD_HTTP_STATUS')[1]||'')),'owner-held provider status set missing');
ok(obs.includes('SEARCH_PROVIDER_BILLING_OR_QUOTA_BLOCKED')&&obs.includes('owner_action'),'owner-held provider stop is not named with an owner action');
ok(obs.includes('stop&&stop.owner_held'),'owner-held branch does not gate the clean exit');
ok(/if\(stop\)\{[\s\S]{0,400}err\.namedStop=stop;throw err;/.test(obs),'non-owner-held provider blackout no longer fails red');
ok(obs.includes('http_status:Number.isInteger(e?.httpStatus)?e.httpStatus:null'),'provider attempts do not record an HTTP status to classify on');
ok(blackoutReport.includes('NAMED_STOP')&&monitor.includes('scripts/search/report_provider_blackout.mjs'),'agency monitor does not report why observation did not happen');
console.log('Live query → competitor → diagnosis → owner-approved repair loop OK.');
