const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=process.cwd();
const outDir=path.join(root,'data','agency');
fs.mkdirSync(outDir,{recursive:true});
const now=new Date();
const liveSite=(process.env.LIVE_SITE_URL||process.env.SITE_DOMAIN||'https://horselegalguide.com').replace(/\/$/,'');
function write(name,value){fs.writeFileSync(path.join(outDir,`${name}_snapshot.json`),JSON.stringify(value,null,2)+'\n');}
function base64url(value){return Buffer.from(value).toString('base64url');}
function dateOnly(d){return d.toISOString().slice(0,10);}
function shiftDays(days){const d=new Date(now);d.setUTCDate(d.getUTCDate()+days);return dateOnly(d);}
async function fetchJson(url,options={}){const res=await fetch(url,{...options,signal:AbortSignal.timeout(Number(process.env.PROVIDER_TIMEOUT_MS||25000))});const text=await res.text();let body;try{body=text?JSON.parse(text):{};}catch{body={raw:text.slice(0,1200)};}if(!res.ok)throw new Error(`${res.status} ${res.statusText}: ${JSON.stringify(body).slice(0,700)}`);return body;}
function serviceAccount(){if(process.env.GSC_SERVICE_ACCOUNT_JSON){try{return JSON.parse(process.env.GSC_SERVICE_ACCOUNT_JSON);}catch(err){throw new Error(`GSC_SERVICE_ACCOUNT_JSON is invalid JSON: ${err.message}`);}}const client_email=process.env.GSC_SERVICE_ACCOUNT_EMAIL;const private_key=(process.env.GSC_PRIVATE_KEY||'').replace(/\\n/g,'\n');return client_email&&private_key?{client_email,private_key}:null;}
async function gscToken(){if(process.env.GSC_ACCESS_TOKEN)return process.env.GSC_ACCESS_TOKEN;const account=serviceAccount();if(!account)return null;const iat=Math.floor(Date.now()/1000);const header=base64url(JSON.stringify({alg:'RS256',typ:'JWT'}));const payload=base64url(JSON.stringify({iss:account.client_email,scope:'https://www.googleapis.com/auth/webmasters.readonly',aud:'https://oauth2.googleapis.com/token',iat,exp:iat+3600}));const input=`${header}.${payload}`;const signature=crypto.sign('RSA-SHA256',Buffer.from(input),account.private_key).toString('base64url');const assertion=`${input}.${signature}`;const token=await fetchJson('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});return token.access_token;}
async function refreshGsc(){const siteUrl=process.env.GSC_SITE_URL||'sc-domain:horselegalguide.com';try{const token=await gscToken();if(!token){write('gsc',{provider:'gsc',status:'not_connected',checked_at:now.toISOString(),site_url:siteUrl,metrics:{},top_queries:[],top_pages:[],query_page:[],daily:[],sitemaps:[],inspections:[],message:'Add GSC service-account secrets or GSC_ACCESS_TOKEN to GitHub Actions.'});return;}
 const analytics=`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/searchAnalytics/query`;
 const query=(startDate,endDate,dimensions,rowLimit=25)=>fetchJson(analytics,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({startDate,endDate,dimensions,rowLimit,type:'web',dataState:'final'})});
 const currentStart=shiftDays(-30),currentEnd=shiftDays(-3),previousStart=shiftDays(-58),previousEnd=shiftDays(-31);
 const sitemapUrl=`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/sitemaps`;
 const [summary,previous,topQueries,topPages,byDate,queryPage,sitemaps]=await Promise.all([query(currentStart,currentEnd,[]),query(previousStart,previousEnd,[]),query(currentStart,currentEnd,['query'],100),query(currentStart,currentEnd,['page'],100),query(currentStart,currentEnd,['date'],60),query(currentStart,currentEnd,['query','page'],25000),fetchJson(sitemapUrl,{headers:{authorization:`Bearer ${token}`}})]);
 const cur=(summary.rows||[{}])[0],prev=(previous.rows||[{}])[0];
 const inspectionLimit=Math.max(0,Math.min(20,Number(process.env.GSC_INSPECTION_LIMIT||10)));const inspections=[];
 for(const row of (topPages.rows||[]).slice(0,inspectionLimit)){const inspectionUrl=String(row.keys?.[0]||'');if(!inspectionUrl)continue;try{const result=await fetchJson('https://searchconsole.googleapis.com/v1/urlInspection/index:inspect',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({inspectionUrl,siteUrl,languageCode:'en-US'})});inspections.push({url:inspectionUrl,ok:true,result:result.inspectionResult||result});}catch(err){inspections.push({url:inspectionUrl,ok:false,error:err.message});}}
 write('gsc',{provider:'gsc',status:'ok',checked_at:now.toISOString(),site_url:siteUrl,date_range:{currentStart,currentEnd,previousStart,previousEnd},metrics:{clicks:cur.clicks||0,impressions:cur.impressions||0,ctr:cur.ctr||0,position:cur.position||0,previous_clicks:prev.clicks||0,previous_impressions:prev.impressions||0,previous_ctr:prev.ctr||0,previous_position:prev.position||0},top_queries:topQueries.rows||[],top_pages:topPages.rows||[],query_page:queryPage.rows||[],daily:byDate.rows||[],sitemaps:sitemaps.sitemap||[],inspections,message:'Search Console monitoring refreshed.'});
 }catch(err){write('gsc',{provider:'gsc',status:'warning',checked_at:now.toISOString(),site_url:siteUrl,metrics:{},top_queries:[],top_pages:[],query_page:[],daily:[],sitemaps:[],inspections:[],message:err.message});}}
async function bingCall(method,params={}){if(!process.env.BING_WEBMASTER_API_KEY)throw new Error('BING_WEBMASTER_API_KEY is not configured.');const url=new URL(`https://ssl.bing.com/webmaster/api.svc/json/${method}`);url.searchParams.set('apikey',process.env.BING_WEBMASTER_API_KEY);for(const [key,value] of Object.entries(params))url.searchParams.set(key,value);const body=await fetchJson(url.toString());return body.d??body;}
async function refreshBing(){const siteUrl=process.env.BING_SITE_URL||'https://horselegalguide.com/';if(!process.env.BING_WEBMASTER_API_KEY){write('bing',{provider:'bing',status:'not_connected',checked_at:now.toISOString(),site_url:siteUrl,metrics:{rank_and_traffic:[],crawl:[]},top_queries:[],message:'Add BING_WEBMASTER_API_KEY and BING_SITE_URL to GitHub Actions.'});return;}try{const [sites,rank,queries,crawl]=await Promise.all([bingCall('GetUserSites'),bingCall('GetRankAndTrafficStats',{siteUrl}),bingCall('GetQueryStats',{siteUrl}),bingCall('GetCrawlStats',{siteUrl})]);const site=(Array.isArray(sites)?sites:[]).find(item=>String(item.Url||item.SiteUrl||'').replace(/\/$/,'')===siteUrl.replace(/\/$/,''));write('bing',{provider:'bing',status:'ok',checked_at:now.toISOString(),site_url:siteUrl,site:site||null,metrics:{rank_and_traffic:Array.isArray(rank)?rank.slice(-120):rank,crawl:Array.isArray(crawl)?crawl.slice(-120):crawl},top_queries:Array.isArray(queries)?queries.slice(0,100):[],message:'Bing Webmaster monitoring refreshed.'});}catch(err){write('bing',{provider:'bing',status:'warning',checked_at:now.toISOString(),site_url:siteUrl,metrics:{rank_and_traffic:[],crawl:[]},top_queries:[],message:err.message});}}
async function refreshLive(){const routes=['/','/coverage/','/reference/','/compare/','/scenario/','/sitemap.xml','/sitemap-pages.xml','/robots.txt','/admin/'];const checks=[];for(const route of routes){const started=Date.now();try{const res=await fetch(liveSite+route,{redirect:'follow',signal:AbortSignal.timeout(15000)});checks.push({route,status:res.status,ok:res.ok,ms:Date.now()-started,content_type:res.headers.get('content-type')||''});}catch(err){checks.push({route,status:0,ok:false,ms:Date.now()-started,error:err.message});}}
 const failures=checks.filter(item=>!item.ok);const environmentUnavailable=failures.length===checks.length&&failures.every(item=>item.status===0);const status=environmentUnavailable?'environment_unavailable':failures.length?'warning':'ok';write('live',{provider:'live',status,checked_at:now.toISOString(),site_url:liveSite,checks,summary:{checked:checks.length,passed:checks.length-failures.length,failed:failures.length},message:environmentUnavailable?'The runner could not reach the public site; scheduled monitoring will retry.':failures.length?`${failures.length} live checks need attention.`:'All monitored public routes returned successful responses.'});}
(async()=>{await Promise.all([refreshGsc(),refreshBing(),refreshLive()]);console.log('Search-health provider snapshots refreshed. Provider warnings do not change approval or publication state.');})().catch(err=>{console.error(`SEARCH MONITOR WARNING: ${err.stack||err.message}`);process.exitCode=0;});
