const fs=require('fs');const path=require('path');
function read(rel,fallback){try{return JSON.parse(fs.readFileSync(path.resolve(process.cwd(),rel),'utf8'));}catch{return fallback;}}
function htmlPath(route){return path.resolve(process.cwd(),'dist',String(route||'/').replace(/^\/+|\/+$/g,''),'index.html');}
function addNoindex(html){if(/<meta[^>]+name=["']robots["']/i.test(html))return html.replace(/<meta[^>]+name=["']robots["'][^>]*>/i,'<meta name="robots" content="noindex,follow">');return html.replace(/<head>/i,'<head><meta name="robots" content="noindex,follow">');}
function replaceCanonical(html,target){const canonical=`https://horselegalguide.com${target}`;if(/<link[^>]+rel=["']canonical["']/i.test(html))return html.replace(/<link[^>]+rel=["']canonical["'][^>]*>/i,`<link rel="canonical" href="${canonical}">`);return html.replace(/<head>/i,`<head><link rel="canonical" href="${canonical}">`);}
function sitemapRemove(xml,route){const loc=`https://horselegalguide.com${route}`;return xml.replace(new RegExp(`<url><loc>${loc.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}</loc>[\\s\\S]*?</url>`,'g'),'');}
function main(){const state=read('data/remediation/applied_search_controls.json',{controls:[]});const controls=state.controls||[];let sitemapFile=path.resolve(process.cwd(),'dist/sitemap-pages.xml');let sitemap=fs.existsSync(sitemapFile)?fs.readFileSync(sitemapFile,'utf8'):'';const redirects=[];const applied=[];for(const control of controls){const file=htmlPath(control.route);if(!fs.existsSync(file))throw new Error(`Applied remediation route is missing from dist: ${control.route}`);let html=fs.readFileSync(file,'utf8');if(control.action==='noindex_keep_llm'){html=addNoindex(html);sitemap=sitemapRemove(sitemap,control.route);}else if(control.action==='canonical_to_primary'){html=replaceCanonical(addNoindex(html),control.target);sitemap=sitemapRemove(sitemap,control.route);}else if(control.action==='redirect_to_primary'){sitemap=sitemapRemove(sitemap,control.route);redirects.push(`${control.route} ${control.target} 301`);}else throw new Error(`Unsupported applied search control: ${control.action}`);fs.writeFileSync(file,html);applied.push(control);}
 if(sitemap)fs.writeFileSync(sitemapFile,sitemap);if(redirects.length){const redirectFile=path.resolve(process.cwd(),'dist/_redirects');let text=fs.existsSync(redirectFile)?fs.readFileSync(redirectFile,'utf8').replace(/\n?# BEGIN OWNER-APPROVED REMEDIATIONS[\s\S]*?# END OWNER-APPROVED REMEDIATIONS\n?/g,'\n').trimEnd():'';text+=`\n\n# BEGIN OWNER-APPROVED REMEDIATIONS\n${redirects.join('\n')}\n# END OWNER-APPROVED REMEDIATIONS\n`;fs.writeFileSync(redirectFile,text);}
 console.log(`Applied ${applied.length} owner-approved search controls to dist.`);return applied;}
if(require.main===module)main();module.exports={main};
