const fs=require('fs');const path=require('path');const {spawnSync}=require('child_process');
function read(rel,fallback){try{return JSON.parse(fs.readFileSync(path.resolve(process.cwd(),rel),'utf8'));}catch{return fallback;}}
function write(rel,value){const file=path.resolve(process.cwd(),rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value,null,2)+'\n');}
function now(){return new Date().toISOString();}
function main(){const operation=process.argv[2]||'dry_run';const approvedAction=process.argv[3]||'';const ids=new Set(process.argv.slice(4));if(operation==='refresh_queue'){require('./build_remediation_queue').main();return;}const queue=read('data/remediation/remediation_queue.json',{proposals:[]});const controls=read('data/remediation/applied_search_controls.json',{schema_version:'1.0.0',controls:[]});const actor=process.env.REQUESTED_BY||'manual-owner';const selected=(queue.proposals||[]).filter(item=>ids.has(item.proposal_id));if(!selected.length)throw new Error('No matching remediation proposals selected.');const allowed=new Set(['noindex_keep_llm','canonical_to_primary','redirect_to_primary','differentiate_patch']);if(operation==='approve'&&!allowed.has(approvedAction))throw new Error(`approved_action must be one of: ${[...allowed].join(', ')}`);const results=[];
 for(const proposal of selected){if(operation==='dry_run'){results.push({proposal_id:proposal.proposal_id,status:proposal.status,suggested_actions:proposal.suggested_actions});continue;}if(operation==='approve'){if(!proposal.suggested_actions.includes(approvedAction)&&approvedAction!=='differentiate_patch')throw new Error(`${approvedAction} is not suggested for ${proposal.proposal_id}`);proposal.status='approved';proposal.approved_action=approvedAction;proposal.approved_by=actor;proposal.approved_at=now();results.push({proposal_id:proposal.proposal_id,status:'approved',action:approvedAction});continue;}if(operation==='reject'){proposal.status='rejected';proposal.rejected_by=actor;proposal.rejected_at=now();results.push({proposal_id:proposal.proposal_id,status:'rejected'});continue;}if(operation==='apply'){if(proposal.status!=='approved'||!proposal.approved_action)throw new Error(`${proposal.proposal_id} is not owner-approved.`);const action=proposal.approved_action;if(action==='differentiate_patch'){if(!proposal.patch_plan)throw new Error(`${proposal.proposal_id} requires a reviewed patch_plan before apply.`);const planFile=path.resolve(process.cwd(),`tmp/${proposal.proposal_id}.json`);fs.mkdirSync(path.dirname(planFile),{recursive:true});fs.writeFileSync(planFile,JSON.stringify(proposal.patch_plan,null,2));const run=spawnSync(process.execPath,['scripts/patch/apply_page_patch.js',planFile],{cwd:process.cwd(),encoding:'utf8'});fs.rmSync(planFile,{force:true});if(run.status!==0)throw new Error(run.stderr||run.stdout||`Patch application failed for ${proposal.proposal_id}`);}else{const routes=proposal.members.filter(route=>route!==proposal.candidate_primary);for(const route of routes){const existing=controls.controls.find(item=>item.proposal_id===proposal.proposal_id&&item.route===route);if(existing)continue;controls.controls.push({proposal_id:proposal.proposal_id,action,route,target:proposal.candidate_primary,approved_by:proposal.approved_by,approved_at:proposal.approved_at,applied_by:actor,applied_at:now()});}}
 proposal.status='applied';proposal.applied_by=actor;proposal.applied_at=now();results.push({proposal_id:proposal.proposal_id,status:'applied',action});continue;}throw new Error(`Unknown remediation operation: ${operation}`);}
 queue.generated_at=now();const counts={};for(const p of queue.proposals||[])counts[p.status]=(counts[p.status]||0)+1;queue.summary={total:queue.proposals.length,pending_owner_approval:counts.pending_owner_approval||0,approved:counts.approved||0,applied:counts.applied||0,rejected:counts.rejected||0};controls.updated_at=now();write('data/remediation/remediation_queue.json',queue);write('data/remediation/applied_search_controls.json',controls);console.log(JSON.stringify({ok:true,operation,results,automatic_approval:false,automatic_live_change:false},null,2));}
try{main();}catch(err){console.error(err.stack||err.message);process.exit(1);}
